spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://13.124.245.202:3306/musicat_temp
      #username: scott
      #password: Tiger_1234
      jdbc-url: jdbc:mysql://localhost:3306/musicat
      username: scott
      password: tiger
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

  mail:
    default-encoding: UTF-8
    port: 465
    host: smtp.naver.com
    username: studydev1234
    password: Qwer1234+
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com

file:
  dir: D:/SpringBootHome/petopia2/src/main/resources/static/upload/

# hibernate가 생성하는 SQL이 모두 보인다.
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

